### PR TITLE
Add OPMissionSDK dependency

### PR DESCRIPTION
**Pull request by DanRStevens**
Add OP2MissionSDK dependency as a Git submodule.

### CODE REVIEW

**Comment by DanRStevens** [comment]
I noticed the LevelTemplate solution file had the comment:
```
# Visual C++ Express 2010
```

Maybe we should check if project files need updating.

**Review by Brett208 — APPROVED** [review]
VS2017 accepts a VS2010 solution file without problem. This compiles and works properly on my computer, so I think we can merge whenever.

If you want, I could recreate the Visual Studio Solution file with VS2017 to bring things into a more modern format.

-Brett

**Comment by Brett208** [comment]
Update: I just realized the Visual Studio did update the solution file automatically after I compiled and ran the code through the debugger. I'd like to post the new solution file. However, it contains Debug, Release, and ReleaseMinSize. I'd like to get rid of one of the two release configurations. If we want the MinSize settings, I would just rename that to Release, but not sure we need those custom settings or not.

-Brett

**Comment by DanRStevens** [comment]
Alright, as it seems to have upgraded silently, I'm going to merge this for now. I've opened Issue #4 to track changes to the solution and project file.

**Pull request merged**
