### PR TITLE
Use quotes for sdk includes

### PR DESCRIPTION
**Pull request by Brett208**

### CODE REVIEW

**Review by DanRStevens — COMMENTED** [review]
Err, weren't we going the other way on this? Wait, no, I read the other PR backwards: https://github.com/OutpostUniverse/HFL/pull/40

Technically it doesn't matter. Though there is a slight difference in the search path used between `""` and `<>`. In this case, we use additional include folders, which impacts both `""` and `<>`. We are not using paths relative to the source file, which is only searched when using `""`.

I sort of feel like angle brackets (`<>`) are more appropriate for external project includes, while quotes (`""`) are more appropriate for internal project includes.

----

Edit: In case this helps:
[What is the difference between `#include <filename>` and `#include “filename”`?](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)

**Comment by Brett208** [comment]
I thought we were using angle bracket for standard library and externally compiled libraries like gtest that are included through packaging systems like nuget/vcpkg. That lines up with OP2Archive and OP2MapImager. It doesn't really bother me either way though.

**Comment by DanRStevens** [comment]
Although the C++ standard leaves the details of file lookup as implementation defined, all major compilers basically do the same thing. The `""` path searching will first try relative from the current file. If `""` patch searching fails, then it falls back to `<>` path searching (that part is specified by the standard). Each compiler will search whatever built in or additional include paths have been configured.

I think for me, the key part is the paths we're using are not relative to the current file. That relative path searching is the main reason to use `""`. Only `""` will search for headers relative to the current file's path, otherwise it is identical to `<>`. Using `""` almost implies you're making use of relative path searching, which we're not.

The Git submodule project dependencies are found using additional include folder project settings, much like how package manager dependencies are found. If you check the terminal window for the build, you can see the `/I` settings for all of them:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /IOP2MissionSDK/ /I"C:\Tools\vcpkg\installed\x86-windows\include" /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /Oy- /GL /D _WINDLL /D _MBCS /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue DllMain.cpp LevelMain.cpp
```
Note the parts: `/IOP2MissionSDK/` and `/I"C:\Tools\vcpkg\installed\x86-windows\include"`

----

On another note, I've recently been giving some thought towards using package managers to handle dependencies on OPU projects. That would bring in pre-compiled outputs. In particular, that could cut down on compile time for projects that depend on the larger libraries, such as OP2Utility, or NAS2D. In that case, we might be switching to a package manager for those dependencies.

**Comment by Brett208** [comment]
Fair enough since we are not including OP2MissionSDK in the include path, it is not actually searching relative to the source code directory.

**Pull request closed without merging**
